image: golang:latest

stages:
    - lint
    - test
    - build
    # - deploy


test_lint:
    stage: lint
    image: golangci/golangci-lint
    script: 
        - golangci-lint run

test_code:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test $(go list ./... | grep -v /vendor/) -v -test.short

build_artefact:
   stage: build
   script:
     - mkdir bin
     - mkdir bin/win
     - mkdir bin/mac
     - mkdir bin/linux
     - GOOS=windows GOARCH=amd64 go build -o bin/win ./...
     - GOOS=darwin GOARCH=amd64 go build -o bin/mac ./...
     - GOOS=linux GOARCH=amd64 go build -o bin/linux ./...
   artifacts:
     paths:
       - bin

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest


# deploy:
#   stage: deploy
#   script: echo "Define your deployment script!"
#   environment: production
